# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'svg_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SvgWidget(object):
    def setupUi(self, SvgWidget):
        SvgWidget.setObjectName("SvgWidget")
        SvgWidget.resize(839, 520)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SvgWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SvgDisplay = QSvgWidget(SvgWidget)
        self.SvgDisplay.setMinimumSize(QtCore.QSize(500, 500))
        self.SvgDisplay.setMaximumSize(QtCore.QSize(500, 500))
        self.SvgDisplay.setObjectName("SvgDisplay")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SvgDisplay)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addWidget(self.SvgDisplay)
        self.line = QtWidgets.QFrame(SvgWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_3 = QtWidgets.QFrame(SvgWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_7.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.toggle_series_label = QtWidgets.QLabel(SvgWidget)
        self.toggle_series_label.setObjectName("toggle_series_label")
        self.verticalLayout_13.addWidget(self.toggle_series_label)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.bst_checkbox = QtWidgets.QCheckBox(SvgWidget)
        self.bst_checkbox.setChecked(True)
        self.bst_checkbox.setObjectName("bst_checkbox")
        self.horizontalLayout_21.addWidget(self.bst_checkbox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem1 = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.wst_checkbox = QtWidgets.QCheckBox(SvgWidget)
        self.wst_checkbox.setChecked(True)
        self.wst_checkbox.setObjectName("wst_checkbox")
        self.horizontalLayout_22.addWidget(self.wst_checkbox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem2 = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.avg_checkbox = QtWidgets.QCheckBox(SvgWidget)
        self.avg_checkbox.setChecked(True)
        self.avg_checkbox.setObjectName("avg_checkbox")
        self.horizontalLayout_23.addWidget(self.avg_checkbox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem3 = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.std_checkbox = QtWidgets.QCheckBox(SvgWidget)
        self.std_checkbox.setChecked(True)
        self.std_checkbox.setObjectName("std_checkbox")
        self.horizontalLayout_24.addWidget(self.std_checkbox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.line_11 = QtWidgets.QFrame(SvgWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_5.addWidget(self.line_11)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SvgWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.n_pop_label = QtWidgets.QLabel(SvgWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_pop_label.sizePolicy().hasHeightForWidth())
        self.n_pop_label.setSizePolicy(sizePolicy)
        self.n_pop_label.setAutoFillBackground(False)
        self.n_pop_label.setObjectName("n_pop_label")
        self.horizontalLayout_6.addWidget(self.n_pop_label)
        self.n_pop_indicator = QtWidgets.QLabel(SvgWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_pop_indicator.sizePolicy().hasHeightForWidth())
        self.n_pop_indicator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.n_pop_indicator.setFont(font)
        self.n_pop_indicator.setAutoFillBackground(False)
        self.n_pop_indicator.setObjectName("n_pop_indicator")
        self.horizontalLayout_6.addWidget(self.n_pop_indicator)
        spacerItem4 = QtWidgets.QSpacerItem(104, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.n_shape_label = QtWidgets.QLabel(SvgWidget)
        self.n_shape_label.setAutoFillBackground(False)
        self.n_shape_label.setObjectName("n_shape_label")
        self.horizontalLayout_14.addWidget(self.n_shape_label)
        self.n_shape_indicator = QtWidgets.QLabel(SvgWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.n_shape_indicator.setFont(font)
        self.n_shape_indicator.setAutoFillBackground(False)
        self.n_shape_indicator.setObjectName("n_shape_indicator")
        self.horizontalLayout_14.addWidget(self.n_shape_indicator)
        spacerItem5 = QtWidgets.QSpacerItem(345, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fitness_label = QtWidgets.QLabel(SvgWidget)
        self.fitness_label.setMaximumSize(QtCore.QSize(55, 16777215))
        self.fitness_label.setAutoFillBackground(False)
        self.fitness_label.setObjectName("fitness_label")
        self.horizontalLayout_7.addWidget(self.fitness_label)
        self.fitness_indicator = QtWidgets.QLabel(SvgWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fitness_indicator.setFont(font)
        self.fitness_indicator.setAutoFillBackground(False)
        self.fitness_indicator.setObjectName("fitness_indicator")
        self.horizontalLayout_7.addWidget(self.fitness_indicator)
        spacerItem6 = QtWidgets.QSpacerItem(3, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iter_label = QtWidgets.QLabel(SvgWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.iter_label.setFont(font)
        self.iter_label.setAutoFillBackground(False)
        self.iter_label.setObjectName("iter_label")
        self.horizontalLayout_3.addWidget(self.iter_label)
        self.iter_indicator = QtWidgets.QLabel(SvgWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.iter_indicator.setFont(font)
        self.iter_indicator.setAutoFillBackground(False)
        self.iter_indicator.setObjectName("iter_indicator")
        self.horizontalLayout_3.addWidget(self.iter_indicator)
        spacerItem7 = QtWidgets.QSpacerItem(40, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.line_10 = QtWidgets.QFrame(SvgWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_7.addWidget(self.line_10)
        self.PltDisplay = FigureWidget(SvgWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PltDisplay.sizePolicy().hasHeightForWidth())
        self.PltDisplay.setSizePolicy(sizePolicy)
        self.PltDisplay.setMinimumSize(QtCore.QSize(300, 250))
        self.PltDisplay.setMaximumSize(QtCore.QSize(500, 16777215))
        self.PltDisplay.setObjectName("PltDisplay")
        self.verticalLayout_7.addWidget(self.PltDisplay)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.line_2 = QtWidgets.QFrame(SvgWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pause_button = QtWidgets.QPushButton(SvgWidget)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_4.addWidget(self.pause_button)
        self.save_button = QtWidgets.QPushButton(SvgWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_4.addWidget(self.save_button)
        self.exit_button = QtWidgets.QPushButton(SvgWidget)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_4.addWidget(self.exit_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(SvgWidget)
        QtCore.QMetaObject.connectSlotsByName(SvgWidget)

    def retranslateUi(self, SvgWidget):
        _translate = QtCore.QCoreApplication.translate
        SvgWidget.setWindowTitle(_translate("SvgWidget", "ImageEvo"))
        self.toggle_series_label.setText(_translate("SvgWidget", "Toggle series:"))
        self.bst_checkbox.setText(_translate("SvgWidget", "Global best"))
        self.wst_checkbox.setText(_translate("SvgWidget", "Global worst"))
        self.avg_checkbox.setText(_translate("SvgWidget", "Average (x̄)"))
        self.std_checkbox.setText(_translate("SvgWidget", "Std. (±σ)"))
        self.label.setText(_translate("SvgWidget", "Stats:"))
        self.n_pop_label.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" color:#000000;\">Population size:</span></p></body></html>"))
        self.n_pop_indicator.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.n_shape_label.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">n_shapes:</span></p></body></html>"))
        self.n_shape_indicator.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.fitness_label.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" color:#000000;\">Fitness:</span></p></body></html>"))
        self.fitness_indicator.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.iter_label.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" color:#000000;\">Iterations:</span></p></body></html>"))
        self.iter_indicator.setText(_translate("SvgWidget", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.pause_button.setText(_translate("SvgWidget", "Pause"))
        self.save_button.setText(_translate("SvgWidget", "Save state"))
        self.exit_button.setText(_translate("SvgWidget", "Exit"))
from PyQt5.QtSvg import QSvgWidget
from figure_widget import FigureWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SvgWidget = QtWidgets.QWidget()
    ui = Ui_SvgWidget()
    ui.setupUi(SvgWidget)
    SvgWidget.show()
    sys.exit(app.exec_())
