# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpso_setup_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GpsoSetupWindow(object):
    def setupUi(self, GpsoSetupWindow):
        GpsoSetupWindow.setObjectName("GpsoSetupWindow")
        GpsoSetupWindow.resize(601, 635)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GpsoSetupWindow.sizePolicy().hasHeightForWidth())
        GpsoSetupWindow.setSizePolicy(sizePolicy)
        GpsoSetupWindow.setMinimumSize(QtCore.QSize(601, 635))
        GpsoSetupWindow.setMaximumSize(QtCore.QSize(601, 635))
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(GpsoSetupWindow)
        self.horizontalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.line_9 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_18.addWidget(self.line_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.line_3 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_8.addWidget(self.line_3)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.gpso_setup_label = QtWidgets.QLabel(GpsoSetupWindow)
        self.gpso_setup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gpso_setup_label.setObjectName("gpso_setup_label")
        self.horizontalLayout_27.addWidget(self.gpso_setup_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.line_11 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_8.addWidget(self.line_11)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.input_folder_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_folder_label.sizePolicy().hasHeightForWidth())
        self.input_folder_label.setSizePolicy(sizePolicy)
        self.input_folder_label.setObjectName("input_folder_label")
        self.horizontalLayout_29.addWidget(self.input_folder_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.input_file_line_edit = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_file_line_edit.sizePolicy().hasHeightForWidth())
        self.input_file_line_edit.setSizePolicy(sizePolicy)
        self.input_file_line_edit.setMinimumSize(QtCore.QSize(184, 25))
        self.input_file_line_edit.setMaximumSize(QtCore.QSize(184, 25))
        self.input_file_line_edit.setText("")
        self.input_file_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_file_line_edit.setObjectName("input_file_line_edit")
        self.horizontalLayout_28.addWidget(self.input_file_line_edit)
        self.input_file_browser = QtWidgets.QToolButton(GpsoSetupWindow)
        self.input_file_browser.setMinimumSize(QtCore.QSize(65, 27))
        self.input_file_browser.setMaximumSize(QtCore.QSize(65, 27))
        self.input_file_browser.setObjectName("input_file_browser")
        self.horizontalLayout_28.addWidget(self.input_file_browser)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.output_folder_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_folder_label.sizePolicy().hasHeightForWidth())
        self.output_folder_label.setSizePolicy(sizePolicy)
        self.output_folder_label.setObjectName("output_folder_label")
        self.horizontalLayout_55.addWidget(self.output_folder_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.output_folder_line_edit = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_folder_line_edit.sizePolicy().hasHeightForWidth())
        self.output_folder_line_edit.setSizePolicy(sizePolicy)
        self.output_folder_line_edit.setMinimumSize(QtCore.QSize(184, 25))
        self.output_folder_line_edit.setMaximumSize(QtCore.QSize(184, 25))
        self.output_folder_line_edit.setText("")
        self.output_folder_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.output_folder_line_edit.setObjectName("output_folder_line_edit")
        self.horizontalLayout_56.addWidget(self.output_folder_line_edit)
        self.output_folder_browser = QtWidgets.QToolButton(GpsoSetupWindow)
        self.output_folder_browser.setMinimumSize(QtCore.QSize(65, 27))
        self.output_folder_browser.setMaximumSize(QtCore.QSize(65, 27))
        self.output_folder_browser.setObjectName("output_folder_browser")
        self.horizontalLayout_56.addWidget(self.output_folder_browser)
        self.verticalLayout_8.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_555 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_555.setObjectName("horizontalLayout_555")
        self.progress_folder_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_folder_label.sizePolicy().hasHeightForWidth())
        self.progress_folder_label.setSizePolicy(sizePolicy)
        self.progress_folder_label.setObjectName("progress_folder_label")
        self.horizontalLayout_555.addWidget(self.progress_folder_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_555.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_555)
        self.horizontalLayout_687 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_687.setObjectName("horizontalLayout_687")
        self.progress_folder_line_edit = QtWidgets.QLineEdit(GpsoSetupWindow)
        self.progress_folder_line_edit.setMinimumSize(QtCore.QSize(184, 25))
        self.progress_folder_line_edit.setMaximumSize(QtCore.QSize(184, 25))
        self.progress_folder_line_edit.setText("")
        self.progress_folder_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progress_folder_line_edit.setObjectName("progress_folder_line_edit")
        self.horizontalLayout_687.addWidget(self.progress_folder_line_edit)
        self.progress_folder_browser = QtWidgets.QToolButton(GpsoSetupWindow)
        self.progress_folder_browser.setMinimumSize(QtCore.QSize(65, 27))
        self.progress_folder_browser.setMaximumSize(QtCore.QSize(65, 27))
        self.progress_folder_browser.setObjectName("progress_folder_browser")
        self.horizontalLayout_687.addWidget(self.progress_folder_browser)
        self.verticalLayout_8.addLayout(self.horizontalLayout_687)
        self.line_2 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.general_options_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_options_label.sizePolicy().hasHeightForWidth())
        self.general_options_label.setSizePolicy(sizePolicy)
        self.general_options_label.setObjectName("general_options_label")
        self.horizontalLayout_3.addWidget(self.general_options_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bg_color_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg_color_label.sizePolicy().hasHeightForWidth())
        self.bg_color_label.setSizePolicy(sizePolicy)
        self.bg_color_label.setMinimumSize(QtCore.QSize(145, 0))
        self.bg_color_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.bg_color_label.setObjectName("bg_color_label")
        self.horizontalLayout_9.addWidget(self.bg_color_label)
        spacerItem4 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.bg_color_dropdown = QtWidgets.QComboBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg_color_dropdown.sizePolicy().hasHeightForWidth())
        self.bg_color_dropdown.setSizePolicy(sizePolicy)
        self.bg_color_dropdown.setMinimumSize(QtCore.QSize(75, 25))
        self.bg_color_dropdown.setMaximumSize(QtCore.QSize(75, 25))
        self.bg_color_dropdown.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.bg_color_dropdown.setObjectName("bg_color_dropdown")
        self.horizontalLayout_9.addWidget(self.bg_color_dropdown)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.output_freq_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_freq_label.sizePolicy().hasHeightForWidth())
        self.output_freq_label.setSizePolicy(sizePolicy)
        self.output_freq_label.setMinimumSize(QtCore.QSize(145, 0))
        self.output_freq_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.output_freq_label.setObjectName("output_freq_label")
        self.horizontalLayout_51.addWidget(self.output_freq_label)
        spacerItem5 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem5)
        self.output_freq_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_freq_entry.sizePolicy().hasHeightForWidth())
        self.output_freq_entry.setSizePolicy(sizePolicy)
        self.output_freq_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.output_freq_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.output_freq_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_freq_entry.setObjectName("output_freq_entry")
        self.horizontalLayout_51.addWidget(self.output_freq_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.save_freq_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_freq_label.sizePolicy().hasHeightForWidth())
        self.save_freq_label.setSizePolicy(sizePolicy)
        self.save_freq_label.setMinimumSize(QtCore.QSize(145, 0))
        self.save_freq_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.save_freq_label.setObjectName("save_freq_label")
        self.horizontalLayout_50.addWidget(self.save_freq_label)
        spacerItem6 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem6)
        self.save_freq_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_freq_entry.sizePolicy().hasHeightForWidth())
        self.save_freq_entry.setSizePolicy(sizePolicy)
        self.save_freq_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.save_freq_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.save_freq_entry.setInputMask("")
        self.save_freq_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.save_freq_entry.setObjectName("save_freq_entry")
        self.horizontalLayout_50.addWidget(self.save_freq_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_50)
        self.line_5 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_8.addWidget(self.line_5)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.w_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_label.sizePolicy().hasHeightForWidth())
        self.w_label.setSizePolicy(sizePolicy)
        self.w_label.setObjectName("w_label")
        self.horizontalLayout_46.addWidget(self.w_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.w0_entry_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w0_entry_label.sizePolicy().hasHeightForWidth())
        self.w0_entry_label.setSizePolicy(sizePolicy)
        self.w0_entry_label.setMinimumSize(QtCore.QSize(145, 0))
        self.w0_entry_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.w0_entry_label.setObjectName("w0_entry_label")
        self.horizontalLayout_47.addWidget(self.w0_entry_label)
        spacerItem8 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem8)
        self.w0_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w0_entry.sizePolicy().hasHeightForWidth())
        self.w0_entry.setSizePolicy(sizePolicy)
        self.w0_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.w0_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.w0_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.w0_entry.setObjectName("w0_entry")
        self.horizontalLayout_47.addWidget(self.w0_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.w1_entry_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w1_entry_label.sizePolicy().hasHeightForWidth())
        self.w1_entry_label.setSizePolicy(sizePolicy)
        self.w1_entry_label.setMinimumSize(QtCore.QSize(145, 0))
        self.w1_entry_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.w1_entry_label.setObjectName("w1_entry_label")
        self.horizontalLayout_48.addWidget(self.w1_entry_label)
        spacerItem9 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem9)
        self.w1_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w1_entry.sizePolicy().hasHeightForWidth())
        self.w1_entry.setSizePolicy(sizePolicy)
        self.w1_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.w1_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.w1_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.w1_entry.setObjectName("w1_entry")
        self.horizontalLayout_48.addWidget(self.w1_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.w2_entry_label_2 = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w2_entry_label_2.sizePolicy().hasHeightForWidth())
        self.w2_entry_label_2.setSizePolicy(sizePolicy)
        self.w2_entry_label_2.setMinimumSize(QtCore.QSize(145, 0))
        self.w2_entry_label_2.setMaximumSize(QtCore.QSize(145, 16777215))
        self.w2_entry_label_2.setObjectName("w2_entry_label_2")
        self.horizontalLayout_49.addWidget(self.w2_entry_label_2)
        spacerItem10 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem10)
        self.w2_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w2_entry.sizePolicy().hasHeightForWidth())
        self.w2_entry.setSizePolicy(sizePolicy)
        self.w2_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.w2_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.w2_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.w2_entry.setObjectName("w2_entry")
        self.horizontalLayout_49.addWidget(self.w2_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_49)
        self.line = QtWidgets.QFrame(GpsoSetupWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.m_rate_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_rate_label.sizePolicy().hasHeightForWidth())
        self.m_rate_label.setSizePolicy(sizePolicy)
        self.m_rate_label.setObjectName("m_rate_label")
        self.horizontalLayout_65.addWidget(self.m_rate_label)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.m_bit_flip_entry_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bit_flip_entry_label.sizePolicy().hasHeightForWidth())
        self.m_bit_flip_entry_label.setSizePolicy(sizePolicy)
        self.m_bit_flip_entry_label.setMinimumSize(QtCore.QSize(145, 0))
        self.m_bit_flip_entry_label.setObjectName("m_bit_flip_entry_label")
        self.horizontalLayout_66.addWidget(self.m_bit_flip_entry_label)
        spacerItem12 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem12)
        self.m_bit_flip_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bit_flip_entry.sizePolicy().hasHeightForWidth())
        self.m_bit_flip_entry.setSizePolicy(sizePolicy)
        self.m_bit_flip_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.m_bit_flip_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.m_bit_flip_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m_bit_flip_entry.setObjectName("m_bit_flip_entry")
        self.horizontalLayout_66.addWidget(self.m_bit_flip_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_66)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.m_shape_swap_entry_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_shape_swap_entry_label.sizePolicy().hasHeightForWidth())
        self.m_shape_swap_entry_label.setSizePolicy(sizePolicy)
        self.m_shape_swap_entry_label.setMinimumSize(QtCore.QSize(145, 0))
        self.m_shape_swap_entry_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.m_shape_swap_entry_label.setObjectName("m_shape_swap_entry_label")
        self.horizontalLayout_67.addWidget(self.m_shape_swap_entry_label)
        spacerItem13 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem13)
        self.m_shape_swap_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_shape_swap_entry.sizePolicy().hasHeightForWidth())
        self.m_shape_swap_entry.setSizePolicy(sizePolicy)
        self.m_shape_swap_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.m_shape_swap_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.m_shape_swap_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.m_shape_swap_entry.setObjectName("m_shape_swap_entry")
        self.horizontalLayout_67.addWidget(self.m_shape_swap_entry)
        self.verticalLayout_8.addLayout(self.horizontalLayout_67)
        spacerItem14 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem14)
        self.line_12 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_8.addWidget(self.line_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem15 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.line_4 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        spacerItem16 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_10 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_11.addWidget(self.line_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shape_type_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_type_label.sizePolicy().hasHeightForWidth())
        self.shape_type_label.setSizePolicy(sizePolicy)
        self.shape_type_label.setObjectName("shape_type_label")
        self.horizontalLayout_2.addWidget(self.shape_type_label)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shape_type_dropdown = QtWidgets.QComboBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_type_dropdown.sizePolicy().hasHeightForWidth())
        self.shape_type_dropdown.setSizePolicy(sizePolicy)
        self.shape_type_dropdown.setMinimumSize(QtCore.QSize(200, 25))
        self.shape_type_dropdown.setMaximumSize(QtCore.QSize(219, 25))
        self.shape_type_dropdown.setObjectName("shape_type_dropdown")
        self.horizontalLayout.addWidget(self.shape_type_dropdown)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.number_of_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_of_label.sizePolicy().hasHeightForWidth())
        self.number_of_label.setSizePolicy(sizePolicy)
        self.number_of_label.setObjectName("number_of_label")
        self.horizontalLayout_40.addWidget(self.number_of_label)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem18)
        self.verticalLayout_11.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.n_vert_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_vert_slider_label.sizePolicy().hasHeightForWidth())
        self.n_vert_slider_label.setSizePolicy(sizePolicy)
        self.n_vert_slider_label.setMinimumSize(QtCore.QSize(110, 0))
        self.n_vert_slider_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.n_vert_slider_label.setObjectName("n_vert_slider_label")
        self.horizontalLayout_44.addWidget(self.n_vert_slider_label)
        self.n_vert_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_vert_slider.sizePolicy().hasHeightForWidth())
        self.n_vert_slider.setSizePolicy(sizePolicy)
        self.n_vert_slider.setMinimumSize(QtCore.QSize(74, 0))
        self.n_vert_slider.setMaximumSize(QtCore.QSize(74, 16777215))
        self.n_vert_slider.setSizeIncrement(QtCore.QSize(0, 0))
        self.n_vert_slider.setBaseSize(QtCore.QSize(0, 0))
        self.n_vert_slider.setMinimum(3)
        self.n_vert_slider.setOrientation(QtCore.Qt.Horizontal)
        self.n_vert_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.n_vert_slider.setTickInterval(0)
        self.n_vert_slider.setObjectName("n_vert_slider")
        self.horizontalLayout_44.addWidget(self.n_vert_slider)
        self.n_vert_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_vert_spinb.sizePolicy().hasHeightForWidth())
        self.n_vert_spinb.setSizePolicy(sizePolicy)
        self.n_vert_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.n_vert_spinb.setMaximumSize(QtCore.QSize(65, 25))
        self.n_vert_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_vert_spinb.setMinimum(1)
        self.n_vert_spinb.setMaximum(999)
        self.n_vert_spinb.setProperty("value", 3)
        self.n_vert_spinb.setObjectName("n_vert_spinb")
        self.horizontalLayout_44.addWidget(self.n_vert_spinb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.init_shape_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_shape_slider_label.sizePolicy().hasHeightForWidth())
        self.init_shape_slider_label.setSizePolicy(sizePolicy)
        self.init_shape_slider_label.setMinimumSize(QtCore.QSize(102, 0))
        self.init_shape_slider_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.init_shape_slider_label.setObjectName("init_shape_slider_label")
        self.horizontalLayout_42.addWidget(self.init_shape_slider_label)
        self.init_shape_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_shape_slider.sizePolicy().hasHeightForWidth())
        self.init_shape_slider.setSizePolicy(sizePolicy)
        self.init_shape_slider.setMinimumSize(QtCore.QSize(74, 0))
        self.init_shape_slider.setMaximumSize(QtCore.QSize(74, 16777215))
        self.init_shape_slider.setMinimum(1)
        self.init_shape_slider.setMaximum(999)
        self.init_shape_slider.setProperty("value", 1)
        self.init_shape_slider.setSliderPosition(1)
        self.init_shape_slider.setOrientation(QtCore.Qt.Horizontal)
        self.init_shape_slider.setObjectName("init_shape_slider")
        self.horizontalLayout_42.addWidget(self.init_shape_slider)
        self.init_shape_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_shape_spinb.sizePolicy().hasHeightForWidth())
        self.init_shape_spinb.setSizePolicy(sizePolicy)
        self.init_shape_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.init_shape_spinb.setMaximumSize(QtCore.QSize(65, 25))
        self.init_shape_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.init_shape_spinb.setMinimum(1)
        self.init_shape_spinb.setMaximum(999)
        self.init_shape_spinb.setProperty("value", 1)
        self.init_shape_spinb.setObjectName("init_shape_spinb")
        self.horizontalLayout_42.addWidget(self.init_shape_spinb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.max_shape_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_shape_slider_label.sizePolicy().hasHeightForWidth())
        self.max_shape_slider_label.setSizePolicy(sizePolicy)
        self.max_shape_slider_label.setMinimumSize(QtCore.QSize(110, 0))
        self.max_shape_slider_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.max_shape_slider_label.setObjectName("max_shape_slider_label")
        self.horizontalLayout_43.addWidget(self.max_shape_slider_label)
        self.max_shape_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_shape_slider.sizePolicy().hasHeightForWidth())
        self.max_shape_slider.setSizePolicy(sizePolicy)
        self.max_shape_slider.setMinimumSize(QtCore.QSize(72, 0))
        self.max_shape_slider.setMaximumSize(QtCore.QSize(74, 16777215))
        self.max_shape_slider.setMinimum(1)
        self.max_shape_slider.setMaximum(999999999)
        self.max_shape_slider.setProperty("value", 64)
        self.max_shape_slider.setSliderPosition(64)
        self.max_shape_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_shape_slider.setObjectName("max_shape_slider")
        self.horizontalLayout_43.addWidget(self.max_shape_slider)
        self.max_shape_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_shape_spinb.sizePolicy().hasHeightForWidth())
        self.max_shape_spinb.setSizePolicy(sizePolicy)
        self.max_shape_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.max_shape_spinb.setMaximumSize(QtCore.QSize(65, 25))
        self.max_shape_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_shape_spinb.setMinimum(1)
        self.max_shape_spinb.setMaximum(999999999)
        self.max_shape_spinb.setProperty("value", 64)
        self.max_shape_spinb.setObjectName("max_shape_spinb")
        self.horizontalLayout_43.addWidget(self.max_shape_spinb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.n_pop_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_pop_slider_label.sizePolicy().hasHeightForWidth())
        self.n_pop_slider_label.setSizePolicy(sizePolicy)
        self.n_pop_slider_label.setMinimumSize(QtCore.QSize(110, 0))
        self.n_pop_slider_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.n_pop_slider_label.setObjectName("n_pop_slider_label")
        self.horizontalLayout_41.addWidget(self.n_pop_slider_label)
        self.n_pop_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_pop_slider.sizePolicy().hasHeightForWidth())
        self.n_pop_slider.setSizePolicy(sizePolicy)
        self.n_pop_slider.setMinimumSize(QtCore.QSize(74, 0))
        self.n_pop_slider.setMaximumSize(QtCore.QSize(74, 16777215))
        self.n_pop_slider.setMinimum(1)
        self.n_pop_slider.setMaximum(2500)
        self.n_pop_slider.setProperty("value", 128)
        self.n_pop_slider.setOrientation(QtCore.Qt.Horizontal)
        self.n_pop_slider.setObjectName("n_pop_slider")
        self.horizontalLayout_41.addWidget(self.n_pop_slider)
        self.n_pop_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_pop_spinb.sizePolicy().hasHeightForWidth())
        self.n_pop_spinb.setSizePolicy(sizePolicy)
        self.n_pop_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.n_pop_spinb.setMaximumSize(QtCore.QSize(65, 25))
        self.n_pop_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_pop_spinb.setMinimum(1)
        self.n_pop_spinb.setMaximum(2500)
        self.n_pop_spinb.setProperty("value", 128)
        self.n_pop_spinb.setObjectName("n_pop_spinb")
        self.horizontalLayout_41.addWidget(self.n_pop_spinb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.shape_management_method_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_management_method_label.sizePolicy().hasHeightForWidth())
        self.shape_management_method_label.setSizePolicy(sizePolicy)
        self.shape_management_method_label.setObjectName("shape_management_method_label")
        self.horizontalLayout_10.addWidget(self.shape_management_method_label)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.shape_management_method_dropdown = QtWidgets.QComboBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_management_method_dropdown.sizePolicy().hasHeightForWidth())
        self.shape_management_method_dropdown.setSizePolicy(sizePolicy)
        self.shape_management_method_dropdown.setMinimumSize(QtCore.QSize(200, 25))
        self.shape_management_method_dropdown.setMaximumSize(QtCore.QSize(219, 25))
        self.shape_management_method_dropdown.setFrame(True)
        self.shape_management_method_dropdown.setObjectName("shape_management_method_dropdown")
        self.horizontalLayout_8.addWidget(self.shape_management_method_dropdown)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.shape_management_value_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_management_value_label.sizePolicy().hasHeightForWidth())
        self.shape_management_value_label.setSizePolicy(sizePolicy)
        self.shape_management_value_label.setMinimumSize(QtCore.QSize(110, 0))
        self.shape_management_value_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.shape_management_value_label.setText("")
        self.shape_management_value_label.setObjectName("shape_management_value_label")
        self.horizontalLayout_5.addWidget(self.shape_management_value_label)
        spacerItem20 = QtWidgets.QSpacerItem(3, 31, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.shape_management_value_entry = QtWidgets.QLineEdit(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_management_value_entry.sizePolicy().hasHeightForWidth())
        self.shape_management_value_entry.setSizePolicy(sizePolicy)
        self.shape_management_value_entry.setMinimumSize(QtCore.QSize(55, 25))
        self.shape_management_value_entry.setMaximumSize(QtCore.QSize(25, 16777215))
        self.shape_management_value_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shape_management_value_entry.setObjectName("shape_management_value_entry")
        self.horizontalLayout_5.addWidget(self.shape_management_value_entry)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.line_6 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_16.addWidget(self.line_6)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.bit_length_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bit_length_label.sizePolicy().hasHeightForWidth())
        self.bit_length_label.setSizePolicy(sizePolicy)
        self.bit_length_label.setObjectName("bit_length_label")
        self.horizontalLayout_39.addWidget(self.bit_length_label)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem21)
        self.verticalLayout_16.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.x_bits_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_bits_slider_label.sizePolicy().hasHeightForWidth())
        self.x_bits_slider_label.setSizePolicy(sizePolicy)
        self.x_bits_slider_label.setMinimumSize(QtCore.QSize(65, 0))
        self.x_bits_slider_label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.x_bits_slider_label.setObjectName("x_bits_slider_label")
        self.horizontalLayout_36.addWidget(self.x_bits_slider_label)
        self.x_bits_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_bits_slider.sizePolicy().hasHeightForWidth())
        self.x_bits_slider.setSizePolicy(sizePolicy)
        self.x_bits_slider.setMinimumSize(QtCore.QSize(119, 0))
        self.x_bits_slider.setMaximumSize(QtCore.QSize(119, 16777215))
        self.x_bits_slider.setMinimum(4)
        self.x_bits_slider.setProperty("value", 7)
        self.x_bits_slider.setOrientation(QtCore.Qt.Horizontal)
        self.x_bits_slider.setObjectName("x_bits_slider")
        self.horizontalLayout_36.addWidget(self.x_bits_slider)
        self.x_bits_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_bits_spinb.sizePolicy().hasHeightForWidth())
        self.x_bits_spinb.setSizePolicy(sizePolicy)
        self.x_bits_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.x_bits_spinb.setMaximumSize(QtCore.QSize(25, 16777215))
        self.x_bits_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x_bits_spinb.setMinimum(4)
        self.x_bits_spinb.setMaximum(99)
        self.x_bits_spinb.setProperty("value", 7)
        self.x_bits_spinb.setObjectName("x_bits_spinb")
        self.horizontalLayout_36.addWidget(self.x_bits_spinb)
        self.verticalLayout_16.addLayout(self.horizontalLayout_36)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.y_bits_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_bits_slider_label.sizePolicy().hasHeightForWidth())
        self.y_bits_slider_label.setSizePolicy(sizePolicy)
        self.y_bits_slider_label.setMinimumSize(QtCore.QSize(65, 0))
        self.y_bits_slider_label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.y_bits_slider_label.setObjectName("y_bits_slider_label")
        self.horizontalLayout_37.addWidget(self.y_bits_slider_label)
        self.y_bits_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_bits_slider.sizePolicy().hasHeightForWidth())
        self.y_bits_slider.setSizePolicy(sizePolicy)
        self.y_bits_slider.setMinimumSize(QtCore.QSize(119, 0))
        self.y_bits_slider.setMaximumSize(QtCore.QSize(119, 16777215))
        self.y_bits_slider.setMinimum(4)
        self.y_bits_slider.setProperty("value", 7)
        self.y_bits_slider.setOrientation(QtCore.Qt.Horizontal)
        self.y_bits_slider.setObjectName("y_bits_slider")
        self.horizontalLayout_37.addWidget(self.y_bits_slider)
        self.y_bits_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_bits_spinb.sizePolicy().hasHeightForWidth())
        self.y_bits_spinb.setSizePolicy(sizePolicy)
        self.y_bits_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.y_bits_spinb.setMaximumSize(QtCore.QSize(65, 25))
        self.y_bits_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.y_bits_spinb.setMaximum(99)
        self.y_bits_spinb.setProperty("value", 7)
        self.y_bits_spinb.setObjectName("y_bits_spinb")
        self.horizontalLayout_37.addWidget(self.y_bits_spinb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.c_bits_slider_label = QtWidgets.QLabel(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_bits_slider_label.sizePolicy().hasHeightForWidth())
        self.c_bits_slider_label.setSizePolicy(sizePolicy)
        self.c_bits_slider_label.setMinimumSize(QtCore.QSize(65, 0))
        self.c_bits_slider_label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.c_bits_slider_label.setObjectName("c_bits_slider_label")
        self.horizontalLayout_38.addWidget(self.c_bits_slider_label)
        self.c_bits_slider = QtWidgets.QSlider(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_bits_slider.sizePolicy().hasHeightForWidth())
        self.c_bits_slider.setSizePolicy(sizePolicy)
        self.c_bits_slider.setMinimumSize(QtCore.QSize(119, 0))
        self.c_bits_slider.setMaximumSize(QtCore.QSize(119, 16777215))
        self.c_bits_slider.setMinimum(1)
        self.c_bits_slider.setMaximum(8)
        self.c_bits_slider.setSingleStep(1)
        self.c_bits_slider.setProperty("value", 8)
        self.c_bits_slider.setOrientation(QtCore.Qt.Horizontal)
        self.c_bits_slider.setObjectName("c_bits_slider")
        self.horizontalLayout_38.addWidget(self.c_bits_slider)
        self.c_bits_spinb = QtWidgets.QSpinBox(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_bits_spinb.sizePolicy().hasHeightForWidth())
        self.c_bits_spinb.setSizePolicy(sizePolicy)
        self.c_bits_spinb.setMinimumSize(QtCore.QSize(65, 25))
        self.c_bits_spinb.setMaximumSize(QtCore.QSize(65, 25))
        self.c_bits_spinb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.c_bits_spinb.setMaximum(8)
        self.c_bits_spinb.setProperty("value", 8)
        self.c_bits_spinb.setObjectName("c_bits_spinb")
        self.horizontalLayout_38.addWidget(self.c_bits_spinb)
        self.verticalLayout_11.addLayout(self.horizontalLayout_38)
        self.line_7 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_11.addWidget(self.line_7)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.oaat_checkbox = QtWidgets.QCheckBox(GpsoSetupWindow)
        self.oaat_checkbox.setChecked(False)
        self.oaat_checkbox.setObjectName("oaat_checkbox")
        self.verticalLayout.addWidget(self.oaat_checkbox)
        self.rollback_checkbox = QtWidgets.QCheckBox(GpsoSetupWindow)
        self.rollback_checkbox.setChecked(True)
        self.rollback_checkbox.setObjectName("rollback_checkbox")
        self.verticalLayout.addWidget(self.rollback_checkbox)
        self.horizontalLayout_45.addLayout(self.verticalLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout_45)
        spacerItem22 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem22)
        self.line_14 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_11.addWidget(self.line_14)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.run_button = QtWidgets.QPushButton(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        self.run_button.setMinimumSize(QtCore.QSize(80, 27))
        self.run_button.setMaximumSize(QtCore.QSize(80, 27))
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_68.addWidget(self.run_button)
        self.back_button = QtWidgets.QPushButton(GpsoSetupWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setMinimumSize(QtCore.QSize(80, 27))
        self.back_button.setMaximumSize(QtCore.QSize(80, 27))
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_68.addWidget(self.back_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_68)
        self.line_8 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_11.addWidget(self.line_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_4)
        self.line_13 = QtWidgets.QFrame(GpsoSetupWindow)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_18.addWidget(self.line_13)

        self.retranslateUi(GpsoSetupWindow)
        QtCore.QMetaObject.connectSlotsByName(GpsoSetupWindow)

    def retranslateUi(self, GpsoSetupWindow):
        _translate = QtCore.QCoreApplication.translate
        GpsoSetupWindow.setWindowTitle(_translate("GpsoSetupWindow", "𝕀mage𝔼vo"))
        self.gpso_setup_label.setText(_translate("GpsoSetupWindow", "GPSO Setup"))
        self.input_folder_label.setToolTip(_translate("GpsoSetupWindow", "The input file path (supported types: jpg, jpeg, jpe, jfif, png)"))
        self.input_folder_label.setText(_translate("GpsoSetupWindow", "Image file:"))
        self.input_file_line_edit.setToolTip(_translate("GpsoSetupWindow", "The input file path (supported types: jpg, jpeg, jpe, jfif, png)"))
        self.input_file_browser.setToolTip(_translate("GpsoSetupWindow", "Browse for input file (supported types: jpg, jpeg, jpe, jfif, png)"))
        self.input_file_browser.setText(_translate("GpsoSetupWindow", "..."))
        self.output_folder_label.setToolTip(_translate("GpsoSetupWindow", "The folder in which to output images"))
        self.output_folder_label.setText(_translate("GpsoSetupWindow", "Output folder:"))
        self.output_folder_line_edit.setToolTip(_translate("GpsoSetupWindow", "Images will be output into this folder (Leave blank for no output)"))
        self.output_folder_browser.setToolTip(_translate("GpsoSetupWindow", "Browse for output folder"))
        self.output_folder_browser.setText(_translate("GpsoSetupWindow", "..."))
        self.progress_folder_label.setToolTip(_translate("GpsoSetupWindow", "The folder in which to output images"))
        self.progress_folder_label.setText(_translate("GpsoSetupWindow", "Progress folder"))
        self.progress_folder_line_edit.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>The population will be saved in this folder (Leave blank to use above output folder)</p></body></html>"))
        self.progress_folder_browser.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>Browse for a folder to save progress of the population</p></body></html>"))
        self.progress_folder_browser.setText(_translate("GpsoSetupWindow", "..."))
        self.general_options_label.setText(_translate("GpsoSetupWindow", "General options:"))
        self.bg_color_label.setText(_translate("GpsoSetupWindow", "    Background color"))
        self.output_freq_label.setToolTip(_translate("GpsoSetupWindow", "Number of iterations to occur between each time an image is ouput (Leave blank or 0 for no output images)"))
        self.output_freq_label.setText(_translate("GpsoSetupWindow", "    Output frequency"))
        self.output_freq_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>Number of iterations to occur between each time an image is ouput (Leave blank or 0 for no output images). Images are output in svg format.</p></body></html>"))
        self.output_freq_entry.setText(_translate("GpsoSetupWindow", "10"))
        self.save_freq_label.setToolTip(_translate("GpsoSetupWindow", "The maximum number of iterations to run"))
        self.save_freq_label.setText(_translate("GpsoSetupWindow", "    Save frequency"))
        self.save_freq_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>The frequency of which progress will be saved (Iterations per save). The entire optimizer/population will be stored in a .pkl file.</p></body></html>"))
        self.save_freq_entry.setText(_translate("GpsoSetupWindow", "100"))
        self.w_label.setText(_translate("GpsoSetupWindow", "Crossover weights:"))
        self.w0_entry_label.setToolTip(_translate("GpsoSetupWindow", "How much to weight an individual\'s current position during crossover"))
        self.w0_entry_label.setText(_translate("GpsoSetupWindow", "    Current"))
        self.w0_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>How much weight/probability to apply to an individual\'s <span style=\" font-style:italic;\">current</span> position during crossover. Constraint: 0 ≤ x ≤ 1. The <span style=\" font-style:italic;\">current</span>, <span style=\" font-style:italic;\">personal best</span> and <span style=\" font-style:italic;\">global best</span> weights must sum to 1; if not they will be divided by their sum when the algorithm is executed.</p></body></html>"))
        self.w0_entry.setText(_translate("GpsoSetupWindow", "0.1"))
        self.w1_entry_label.setToolTip(_translate("GpsoSetupWindow", "How much to weight an individual\'s personal best position during crossover"))
        self.w1_entry_label.setText(_translate("GpsoSetupWindow", "    Personal Best"))
        self.w1_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>How much weight/probability to apply to an individual\'s <span style=\" font-style:italic;\">personal best</span> position during crossover. Recommended: 0 ≤ x ≤ 1. The <span style=\" font-style:italic;\">current</span>, <span style=\" font-style:italic;\">personal best</span> and <span style=\" font-style:italic;\">global best</span> weights must sum to 1; if not they will be divided by their sum when the algorithm is executed.</p></body></html>"))
        self.w1_entry.setText(_translate("GpsoSetupWindow", "0.45"))
        self.w2_entry_label_2.setToolTip(_translate("GpsoSetupWindow", "How much to weight the global best position during crossover"))
        self.w2_entry_label_2.setText(_translate("GpsoSetupWindow", "    Global Best"))
        self.w2_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>How much weight/probability to apply to the <span style=\" font-style:italic;\">global best</span> position during crossover. Recommended: 0 ≤ x ≤ 1. The <span style=\" font-style:italic;\">current</span>, <span style=\" font-style:italic;\">personal best</span> and <span style=\" font-style:italic;\">global best</span> weights must sum to 1; if not they will be divided by their sum when the algorithm is executed.</p></body></html>"))
        self.w2_entry.setText(_translate("GpsoSetupWindow", "0.45"))
        self.m_rate_label.setText(_translate("GpsoSetupWindow", "Mutation rate:"))
        self.m_bit_flip_entry_label.setToolTip(_translate("GpsoSetupWindow", "The probability of a single bit flipping "))
        self.m_bit_flip_entry_label.setText(_translate("GpsoSetupWindow", "    Bit flip"))
        self.m_bit_flip_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>The probability of a single bit flipping (constraint: 0 ≤ x ≤ 1)</p></body></html>"))
        self.m_bit_flip_entry.setText(_translate("GpsoSetupWindow", "1e-5"))
        self.m_shape_swap_entry_label.setToolTip(_translate("GpsoSetupWindow", "The probability that a single individual will have the order of the shapes in its DNA swapped"))
        self.m_shape_swap_entry_label.setText(_translate("GpsoSetupWindow", "    Shape swap"))
        self.m_shape_swap_entry.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>The probability that a single individual will have the order of the shapes in its DNA swapped (constraint: 0 ≤ x ≤ 1)</p></body></html>"))
        self.m_shape_swap_entry.setText(_translate("GpsoSetupWindow", "0"))
        self.shape_type_label.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>Select a primative shape type</p></body></html>"))
        self.shape_type_label.setText(_translate("GpsoSetupWindow", "Shape type:"))
        self.shape_type_dropdown.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>Select a primative shape type</p></body></html>"))
        self.number_of_label.setText(_translate("GpsoSetupWindow", "Number of:"))
        self.n_vert_slider_label.setToolTip(_translate("GpsoSetupWindow", "The number of vertices a shape will possess"))
        self.n_vert_slider_label.setText(_translate("GpsoSetupWindow", "    Vertices"))
        self.n_vert_slider.setToolTip(_translate("GpsoSetupWindow", "The number of vertices a shape will possess "))
        self.n_vert_spinb.setToolTip(_translate("GpsoSetupWindow", "The number of vertices a shape will possess"))
        self.init_shape_slider_label.setToolTip(_translate("GpsoSetupWindow", "The initial number of shapes an individual solution will possess"))
        self.init_shape_slider_label.setText(_translate("GpsoSetupWindow", "    Init. shapes"))
        self.init_shape_slider.setToolTip(_translate("GpsoSetupWindow", "The initial number of shapes an individual solution will possess"))
        self.init_shape_spinb.setToolTip(_translate("GpsoSetupWindow", "The initial number of shapes an individual solution will possess"))
        self.max_shape_slider_label.setToolTip(_translate("GpsoSetupWindow", "The maximum number of shapes an individual solution will possess"))
        self.max_shape_slider_label.setText(_translate("GpsoSetupWindow", "    Max. shapes"))
        self.max_shape_slider.setToolTip(_translate("GpsoSetupWindow", "The maximum number of shapes an individual solution will possess"))
        self.max_shape_spinb.setToolTip(_translate("GpsoSetupWindow", "The maximum number of shapes an individual solution will possess"))
        self.n_pop_slider_label.setToolTip(_translate("GpsoSetupWindow", "The size of the population of solutions"))
        self.n_pop_slider_label.setText(_translate("GpsoSetupWindow", "    Solutions"))
        self.n_pop_slider.setToolTip(_translate("GpsoSetupWindow", "The size of the population of solutions"))
        self.n_pop_spinb.setToolTip(_translate("GpsoSetupWindow", "The size of the population of solutions"))
        self.shape_management_method_label.setText(_translate("GpsoSetupWindow", "Shape management method:"))
        self.shape_management_method_dropdown.setToolTip(_translate("GpsoSetupWindow", "<html><head/><body><p>The method by which to increase the number of shapes:</p><p><br/></p><p>probabilistic - at each iteration a random float is generated and if it exceeds a chosen probability, a new shape is generated</p><p><br/></p><p>velocity - if the global best does not improve for a set number of iterations a new shape is generated</p><p><br/></p><p>periodic - a new shape is generated everytime a set number of iterations occurs</p></body></html>"))
        self.bit_length_label.setText(_translate("GpsoSetupWindow", "Bit lengths:"))
        self.x_bits_slider_label.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the x dimension"))
        self.x_bits_slider_label.setText(_translate("GpsoSetupWindow", "    X"))
        self.x_bits_slider.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the x dimension"))
        self.x_bits_spinb.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the x dimension"))
        self.y_bits_slider_label.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the y dimension"))
        self.y_bits_slider_label.setText(_translate("GpsoSetupWindow", "    Y"))
        self.y_bits_slider.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the y dimension"))
        self.y_bits_spinb.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the y dimension"))
        self.c_bits_slider_label.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the rgba color dimensions"))
        self.c_bits_slider_label.setText(_translate("GpsoSetupWindow", "    RGBA     "))
        self.c_bits_slider.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the rgba color dimensions"))
        self.c_bits_spinb.setToolTip(_translate("GpsoSetupWindow", "The number of bits used to represent the rgba color dimensions"))
        self.oaat_checkbox.setToolTip(_translate("GpsoSetupWindow", "Whether or not to use the One At A Time version of the algorithm which basically optimizes a single shape at a time. This approach is much faster but sacrifices some fitness of the solutions obtained."))
        self.oaat_checkbox.setText(_translate("GpsoSetupWindow", "OAAT"))
        self.rollback_checkbox.setToolTip(_translate("GpsoSetupWindow", "If we consider a case where a shape (A) has been initialized and the algorithm runs untill the next shape is initialized, shape B, the global obtained through optimizing shape A may be worse than it was before A was initialized. Basically, the algorithm has gotten stuck in a local optimum. To attempt to avoid this happening we can allow the algorithm to roll back to a previous state, when shape A was initialized, and the new randomly initialized shape A may lead to better solutions and not get stuck."))
        self.rollback_checkbox.setText(_translate("GpsoSetupWindow", "Rollback"))
        self.run_button.setToolTip(_translate("GpsoSetupWindow", "Return to previous screen"))
        self.run_button.setText(_translate("GpsoSetupWindow", "Run"))
        self.back_button.setToolTip(_translate("GpsoSetupWindow", "Execute the algorithm"))
        self.back_button.setText(_translate("GpsoSetupWindow", "Back"))

