# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulated_annealing_display_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulatedAnnealingDisplayWindow(object):
    def setupUi(self, SimulatedAnnealingDisplayWindow):
        SimulatedAnnealingDisplayWindow.setObjectName("SimulatedAnnealingDisplayWindow")
        SimulatedAnnealingDisplayWindow.resize(1165, 626)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SimulatedAnnealingDisplayWindow)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtWidgets.QFrame(SimulatedAnnealingDisplayWindow)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.svg_widget = QSvgWidget(SimulatedAnnealingDisplayWindow)
        self.svg_widget.setMinimumSize(QtCore.QSize(500, 500))
        self.svg_widget.setMaximumSize(QtCore.QSize(500, 500))
        self.svg_widget.setObjectName("svg_widget")
        self.horizontalLayout.addWidget(self.svg_widget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_3 = QtWidgets.QFrame(SimulatedAnnealingDisplayWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_7.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.toggle_series_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        self.toggle_series_label.setObjectName("toggle_series_label")
        self.verticalLayout_13.addWidget(self.toggle_series_label)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.dst_checkbox = QtWidgets.QCheckBox(SimulatedAnnealingDisplayWindow)
        self.dst_checkbox.setChecked(True)
        self.dst_checkbox.setObjectName("dst_checkbox")
        self.horizontalLayout_21.addWidget(self.dst_checkbox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.line_5 = QtWidgets.QFrame(SimulatedAnnealingDisplayWindow)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_11.addWidget(self.line_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.n_shape_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        self.n_shape_label.setAutoFillBackground(False)
        self.n_shape_label.setObjectName("n_shape_label")
        self.horizontalLayout_15.addWidget(self.n_shape_label)
        self.n_shape_indicator = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.n_shape_indicator.setFont(font)
        self.n_shape_indicator.setAutoFillBackground(False)
        self.n_shape_indicator.setObjectName("n_shape_indicator")
        self.horizontalLayout_15.addWidget(self.n_shape_indicator)
        spacerItem1 = QtWidgets.QSpacerItem(345, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.fitness_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        self.fitness_label.setMaximumSize(QtCore.QSize(55, 16777215))
        self.fitness_label.setAutoFillBackground(False)
        self.fitness_label.setObjectName("fitness_label")
        self.horizontalLayout_13.addWidget(self.fitness_label)
        self.fitness_indicator = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fitness_indicator.setFont(font)
        self.fitness_indicator.setAutoFillBackground(False)
        self.fitness_indicator.setObjectName("fitness_indicator")
        self.horizontalLayout_13.addWidget(self.fitness_indicator)
        spacerItem2 = QtWidgets.QSpacerItem(3, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.distance_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_label.sizePolicy().hasHeightForWidth())
        self.distance_label.setSizePolicy(sizePolicy)
        self.distance_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.distance_label.setAutoFillBackground(False)
        self.distance_label.setObjectName("distance_label")
        self.horizontalLayout_16.addWidget(self.distance_label)
        self.distance_indicator = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.distance_indicator.setFont(font)
        self.distance_indicator.setAutoFillBackground(False)
        self.distance_indicator.setObjectName("distance_indicator")
        self.horizontalLayout_16.addWidget(self.distance_indicator)
        spacerItem3 = QtWidgets.QSpacerItem(3, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.iter_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.iter_label.setFont(font)
        self.iter_label.setAutoFillBackground(False)
        self.iter_label.setObjectName("iter_label")
        self.horizontalLayout_17.addWidget(self.iter_label)
        self.iter_indicator = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.iter_indicator.setFont(font)
        self.iter_indicator.setAutoFillBackground(False)
        self.iter_indicator.setObjectName("iter_indicator")
        self.horizontalLayout_17.addWidget(self.iter_indicator)
        spacerItem4 = QtWidgets.QSpacerItem(40, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.update_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_label.sizePolicy().hasHeightForWidth())
        self.update_label.setSizePolicy(sizePolicy)
        self.update_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.update_label.setSizeIncrement(QtCore.QSize(180, 0))
        self.update_label.setAutoFillBackground(False)
        self.update_label.setObjectName("update_label")
        self.horizontalLayout_19.addWidget(self.update_label)
        self.isi_indicator = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.isi_indicator.setFont(font)
        self.isi_indicator.setAutoFillBackground(False)
        self.isi_indicator.setObjectName("isi_indicator")
        self.horizontalLayout_19.addWidget(self.isi_indicator)
        spacerItem5 = QtWidgets.QSpacerItem(50, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_11)
        self.line_11 = QtWidgets.QFrame(SimulatedAnnealingDisplayWindow)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_5.addWidget(self.line_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.line_10 = QtWidgets.QFrame(SimulatedAnnealingDisplayWindow)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_7.addWidget(self.line_10)
        self.MplDisplay = HillClimberFigureWidget(SimulatedAnnealingDisplayWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplDisplay.sizePolicy().hasHeightForWidth())
        self.MplDisplay.setSizePolicy(sizePolicy)
        self.MplDisplay.setMinimumSize(QtCore.QSize(500, 250))
        self.MplDisplay.setMaximumSize(QtCore.QSize(700, 16777215))
        self.MplDisplay.setObjectName("MplDisplay")
        self.verticalLayout_7.addWidget(self.MplDisplay)
        self.message_label = QtWidgets.QLabel(SimulatedAnnealingDisplayWindow)
        self.message_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.message_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.message_label.setLineWidth(0)
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.verticalLayout_7.addWidget(self.message_label)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.line_2 = QtWidgets.QFrame(SimulatedAnnealingDisplayWindow)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pause_button = QtWidgets.QPushButton(SimulatedAnnealingDisplayWindow)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_4.addWidget(self.pause_button)
        self.save_button = QtWidgets.QPushButton(SimulatedAnnealingDisplayWindow)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_4.addWidget(self.save_button)
        self.exit_button = QtWidgets.QPushButton(SimulatedAnnealingDisplayWindow)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_4.addWidget(self.exit_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(SimulatedAnnealingDisplayWindow)
        QtCore.QMetaObject.connectSlotsByName(SimulatedAnnealingDisplayWindow)

    def retranslateUi(self, SimulatedAnnealingDisplayWindow):
        _translate = QtCore.QCoreApplication.translate
        SimulatedAnnealingDisplayWindow.setWindowTitle(_translate("SimulatedAnnealingDisplayWindow", "𝕀mage𝔼vo"))
        self.toggle_series_label.setText(_translate("SimulatedAnnealingDisplayWindow", "Toggle series:"))
        self.dst_checkbox.setText(_translate("SimulatedAnnealingDisplayWindow", "Current distance"))
        self.label_2.setText(_translate("SimulatedAnnealingDisplayWindow", "Stats:"))
        self.n_shape_label.setToolTip(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p>The number of shapes possessed by an individual solution.</p></body></html>"))
        self.n_shape_label.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" color:#000000;\">n_shape:</span></p></body></html>"))
        self.n_shape_indicator.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.fitness_label.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" color:#000000;\">Fitness:</span></p></body></html>"))
        self.fitness_indicator.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.distance_label.setToolTip(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p>The distance (squared euclidean) between the globals best and original image.</p></body></html>"))
        self.distance_label.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" color:#000000;\">Distance:</span></p></body></html>"))
        self.distance_indicator.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.iter_label.setToolTip(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p>Number of iterations of the algorithm since it was instantiated.</p></body></html>"))
        self.iter_label.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" color:#000000;\">Iterations:</span></p></body></html>"))
        self.iter_indicator.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.update_label.setToolTip(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p>The number of iterations since a new global best was achieved.</p></body></html>"))
        self.update_label.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" color:#000000;\">Iter. since improvement:</span></p></body></html>"))
        self.isi_indicator.setText(_translate("SimulatedAnnealingDisplayWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">0</span></p></body></html>"))
        self.pause_button.setText(_translate("SimulatedAnnealingDisplayWindow", "Pause"))
        self.save_button.setText(_translate("SimulatedAnnealingDisplayWindow", "Save state"))
        self.exit_button.setText(_translate("SimulatedAnnealingDisplayWindow", "Exit"))

from PyQt5.QtSvg import QSvgWidget
from ui.matplotlib_widgets import HillClimberFigureWidget
