# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_maker_setup_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoMakerSetup(object):
    def setupUi(self, VideoMakerSetup):
        VideoMakerSetup.setObjectName("VideoMakerSetup")
        VideoMakerSetup.setEnabled(True)
        VideoMakerSetup.resize(357, 626)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoMakerSetup.sizePolicy().hasHeightForWidth())
        VideoMakerSetup.setSizePolicy(sizePolicy)
        VideoMakerSetup.setMinimumSize(QtCore.QSize(357, 626))
        VideoMakerSetup.setMaximumSize(QtCore.QSize(357, 626))
        self._2 = QtWidgets.QVBoxLayout(VideoMakerSetup)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self._2.setContentsMargins(9, -1, 13, 9)
        self._2.setSpacing(9)
        self._2.setObjectName("_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_3 = QtWidgets.QFrame(VideoMakerSetup)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_8 = QtWidgets.QFrame(VideoMakerSetup)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_editor_label_2 = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_editor_label_2.sizePolicy().hasHeightForWidth())
        self.image_editor_label_2.setSizePolicy(sizePolicy)
        self.image_editor_label_2.setMinimumSize(QtCore.QSize(100, 27))
        self.image_editor_label_2.setMaximumSize(QtCore.QSize(100, 27))
        self.image_editor_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_editor_label_2.setObjectName("image_editor_label_2")
        self.horizontalLayout_2.addWidget(self.image_editor_label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem1 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem1)
        self.img_widget = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_widget.sizePolicy().hasHeightForWidth())
        self.img_widget.setSizePolicy(sizePolicy)
        self.img_widget.setMinimumSize(QtCore.QSize(100, 100))
        self.img_widget.setMaximumSize(QtCore.QSize(100, 100))
        self.img_widget.setText("")
        self.img_widget.setPixmap(QtGui.QPixmap("../img/gfx/tv_img.svg"))
        self.img_widget.setScaledContents(True)
        self.img_widget.setObjectName("img_widget")
        self.horizontalLayout_28.addWidget(self.img_widget)
        spacerItem2 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.save_as_label = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_as_label.sizePolicy().hasHeightForWidth())
        self.save_as_label.setSizePolicy(sizePolicy)
        self.save_as_label.setObjectName("save_as_label")
        self.horizontalLayout_35.addWidget(self.save_as_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.save_as_line_edit = QtWidgets.QLineEdit(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_as_line_edit.sizePolicy().hasHeightForWidth())
        self.save_as_line_edit.setSizePolicy(sizePolicy)
        self.save_as_line_edit.setMinimumSize(QtCore.QSize(184, 25))
        self.save_as_line_edit.setMaximumSize(QtCore.QSize(184, 25))
        self.save_as_line_edit.setText("")
        self.save_as_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.save_as_line_edit.setObjectName("save_as_line_edit")
        self.horizontalLayout_34.addWidget(self.save_as_line_edit)
        self.save_as_file_browser = QtWidgets.QToolButton(VideoMakerSetup)
        self.save_as_file_browser.setMinimumSize(QtCore.QSize(65, 27))
        self.save_as_file_browser.setMaximumSize(QtCore.QSize(65, 27))
        self.save_as_file_browser.setObjectName("save_as_file_browser")
        self.horizontalLayout_34.addWidget(self.save_as_file_browser)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.input_folder_label_2 = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_folder_label_2.sizePolicy().hasHeightForWidth())
        self.input_folder_label_2.setSizePolicy(sizePolicy)
        self.input_folder_label_2.setObjectName("input_folder_label_2")
        self.horizontalLayout_31.addWidget(self.input_folder_label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.svg_folder_line_edit = QtWidgets.QLineEdit(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.svg_folder_line_edit.sizePolicy().hasHeightForWidth())
        self.svg_folder_line_edit.setSizePolicy(sizePolicy)
        self.svg_folder_line_edit.setMinimumSize(QtCore.QSize(184, 25))
        self.svg_folder_line_edit.setMaximumSize(QtCore.QSize(184, 25))
        self.svg_folder_line_edit.setText("")
        self.svg_folder_line_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.svg_folder_line_edit.setObjectName("svg_folder_line_edit")
        self.horizontalLayout_30.addWidget(self.svg_folder_line_edit)
        self.svg_folder_browser = QtWidgets.QToolButton(VideoMakerSetup)
        self.svg_folder_browser.setMinimumSize(QtCore.QSize(65, 27))
        self.svg_folder_browser.setMaximumSize(QtCore.QSize(65, 27))
        self.svg_folder_browser.setObjectName("svg_folder_browser")
        self.horizontalLayout_30.addWidget(self.svg_folder_browser)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.line_6 = QtWidgets.QFrame(VideoMakerSetup)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.verticalLayout_2.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.video_codec_label = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_codec_label.sizePolicy().hasHeightForWidth())
        self.video_codec_label.setSizePolicy(sizePolicy)
        self.video_codec_label.setMinimumSize(QtCore.QSize(145, 0))
        self.video_codec_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.video_codec_label.setObjectName("video_codec_label")
        self.horizontalLayout_11.addWidget(self.video_codec_label)
        spacerItem5 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.video_codec_dropdown = QtWidgets.QComboBox(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_codec_dropdown.sizePolicy().hasHeightForWidth())
        self.video_codec_dropdown.setSizePolicy(sizePolicy)
        self.video_codec_dropdown.setMinimumSize(QtCore.QSize(75, 25))
        self.video_codec_dropdown.setMaximumSize(QtCore.QSize(75, 25))
        self.video_codec_dropdown.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.video_codec_dropdown.setObjectName("video_codec_dropdown")
        self.horizontalLayout_11.addWidget(self.video_codec_dropdown)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.container_label = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container_label.sizePolicy().hasHeightForWidth())
        self.container_label.setSizePolicy(sizePolicy)
        self.container_label.setMinimumSize(QtCore.QSize(145, 0))
        self.container_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.container_label.setObjectName("container_label")
        self.horizontalLayout_12.addWidget(self.container_label)
        spacerItem6 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.container_dropdown = QtWidgets.QComboBox(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container_dropdown.sizePolicy().hasHeightForWidth())
        self.container_dropdown.setSizePolicy(sizePolicy)
        self.container_dropdown.setMinimumSize(QtCore.QSize(75, 25))
        self.container_dropdown.setMaximumSize(QtCore.QSize(75, 25))
        self.container_dropdown.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.container_dropdown.setObjectName("container_dropdown")
        self.horizontalLayout_12.addWidget(self.container_dropdown)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.resolution_label = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolution_label.sizePolicy().hasHeightForWidth())
        self.resolution_label.setSizePolicy(sizePolicy)
        self.resolution_label.setMinimumSize(QtCore.QSize(145, 0))
        self.resolution_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.resolution_label.setObjectName("resolution_label")
        self.horizontalLayout_10.addWidget(self.resolution_label)
        spacerItem7 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.resolution_dropdown = QtWidgets.QComboBox(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolution_dropdown.sizePolicy().hasHeightForWidth())
        self.resolution_dropdown.setSizePolicy(sizePolicy)
        self.resolution_dropdown.setMinimumSize(QtCore.QSize(75, 25))
        self.resolution_dropdown.setMaximumSize(QtCore.QSize(75, 25))
        self.resolution_dropdown.setToolTip("")
        self.resolution_dropdown.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.resolution_dropdown.setObjectName("resolution_dropdown")
        self.horizontalLayout_10.addWidget(self.resolution_dropdown)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.fps_label = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fps_label.sizePolicy().hasHeightForWidth())
        self.fps_label.setSizePolicy(sizePolicy)
        self.fps_label.setMinimumSize(QtCore.QSize(145, 0))
        self.fps_label.setMaximumSize(QtCore.QSize(145, 16777215))
        self.fps_label.setObjectName("fps_label")
        self.horizontalLayout_9.addWidget(self.fps_label)
        spacerItem8 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.fps_entry = QtWidgets.QLineEdit(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fps_entry.sizePolicy().hasHeightForWidth())
        self.fps_entry.setSizePolicy(sizePolicy)
        self.fps_entry.setMinimumSize(QtCore.QSize(65, 25))
        self.fps_entry.setMaximumSize(QtCore.QSize(65, 25))
        self.fps_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fps_entry.setObjectName("fps_entry")
        self.horizontalLayout_9.addWidget(self.fps_entry)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.line_2 = QtWidgets.QFrame(VideoMakerSetup)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.resolution_label_4 = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolution_label_4.sizePolicy().hasHeightForWidth())
        self.resolution_label_4.setSizePolicy(sizePolicy)
        self.resolution_label_4.setMinimumSize(QtCore.QSize(130, 27))
        self.resolution_label_4.setMaximumSize(QtCore.QSize(130, 27))
        self.resolution_label_4.setObjectName("resolution_label_4")
        self.horizontalLayout_16.addWidget(self.resolution_label_4)
        spacerItem9 = QtWidgets.QSpacerItem(164, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(35, 14, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.sampling_method_dropdown = QtWidgets.QComboBox(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampling_method_dropdown.sizePolicy().hasHeightForWidth())
        self.sampling_method_dropdown.setSizePolicy(sizePolicy)
        self.sampling_method_dropdown.setMinimumSize(QtCore.QSize(240, 25))
        self.sampling_method_dropdown.setMaximumSize(QtCore.QSize(240, 25))
        self.sampling_method_dropdown.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.sampling_method_dropdown.setObjectName("sampling_method_dropdown")
        self.horizontalLayout_13.addWidget(self.sampling_method_dropdown)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem11 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.label = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(33, 0))
        self.label.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem13 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.start_entry = QtWidgets.QLineEdit(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_entry.sizePolicy().hasHeightForWidth())
        self.start_entry.setSizePolicy(sizePolicy)
        self.start_entry.setMinimumSize(QtCore.QSize(75, 25))
        self.start_entry.setMaximumSize(QtCore.QSize(75, 25))
        self.start_entry.setText("")
        self.start_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_entry.setObjectName("start_entry")
        self.horizontalLayout_14.addWidget(self.start_entry)
        spacerItem14 = QtWidgets.QSpacerItem(35, 12, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.label_2 = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(33, 0))
        self.label_2.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        spacerItem15 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.step_entry = QtWidgets.QLineEdit(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_entry.sizePolicy().hasHeightForWidth())
        self.step_entry.setSizePolicy(sizePolicy)
        self.step_entry.setMinimumSize(QtCore.QSize(75, 25))
        self.step_entry.setMaximumSize(QtCore.QSize(75, 25))
        self.step_entry.setText("")
        self.step_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.step_entry.setObjectName("step_entry")
        self.horizontalLayout_14.addWidget(self.step_entry)
        spacerItem16 = QtWidgets.QSpacerItem(80, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem17 = QtWidgets.QSpacerItem(14, 12, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.label_4 = QtWidgets.QLabel(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(33, 0))
        self.label_4.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        spacerItem18 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.stop_entry = QtWidgets.QLineEdit(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_entry.sizePolicy().hasHeightForWidth())
        self.stop_entry.setSizePolicy(sizePolicy)
        self.stop_entry.setMinimumSize(QtCore.QSize(75, 25))
        self.stop_entry.setMaximumSize(QtCore.QSize(75, 25))
        self.stop_entry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stop_entry.setObjectName("stop_entry")
        self.horizontalLayout_15.addWidget(self.stop_entry)
        spacerItem19 = QtWidgets.QSpacerItem(192, 12, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.line_5 = QtWidgets.QFrame(VideoMakerSetup)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.run_button = QtWidgets.QPushButton(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        self.run_button.setMinimumSize(QtCore.QSize(80, 27))
        self.run_button.setMaximumSize(QtCore.QSize(80, 27))
        self.run_button.setToolTip("")
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_68.addWidget(self.run_button)
        self.exit_button = QtWidgets.QPushButton(VideoMakerSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setMinimumSize(QtCore.QSize(80, 27))
        self.exit_button.setMaximumSize(QtCore.QSize(80, 27))
        self.exit_button.setToolTip("")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_68.addWidget(self.exit_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_68)
        self.line = QtWidgets.QFrame(VideoMakerSetup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_4 = QtWidgets.QFrame(VideoMakerSetup)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self._2.addLayout(self.horizontalLayout)

        self.retranslateUi(VideoMakerSetup)
        QtCore.QMetaObject.connectSlotsByName(VideoMakerSetup)

    def retranslateUi(self, VideoMakerSetup):
        _translate = QtCore.QCoreApplication.translate
        VideoMakerSetup.setWindowTitle(_translate("VideoMakerSetup", "𝕀mage𝔼vo"))
        self.image_editor_label_2.setText(_translate("VideoMakerSetup", "<html><head/><body><p><span style=\" font-weight:600;\">Video Maker</span></p></body></html>"))
        self.save_as_label.setToolTip(_translate("VideoMakerSetup", "The input file path (supported types: jpg, jpeg, jpe, jfif, png)"))
        self.save_as_label.setText(_translate("VideoMakerSetup", "Save as"))
        self.save_as_line_edit.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>Where the video file should be saved and what it should be named.</p></body></html>"))
        self.save_as_file_browser.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>Where the video file should be saved and what it should be named.<br/></p></body></html>"))
        self.save_as_file_browser.setText(_translate("VideoMakerSetup", "..."))
        self.input_folder_label_2.setToolTip(_translate("VideoMakerSetup", "The input file path (supported types: jpg, jpeg, jpe, jfif, png)"))
        self.input_folder_label_2.setText(_translate("VideoMakerSetup", "SVG folder"))
        self.svg_folder_line_edit.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>Browse for folder containing SVG file outputs from a run of ImageEvo.</p><p>If running VideoMaker straight after ImageEvo, the text box should be populated with the correct folder.</p></body></html>"))
        self.svg_folder_browser.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>Browse for folder containing SVG file outputs from a run of ImageEvo.</p><p>If running VideoMaker straight after ImageEvo, the text box should be populated with the correct folder.</p></body></html>"))
        self.svg_folder_browser.setText(_translate("VideoMakerSetup", "..."))
        self.video_codec_label.setText(_translate("VideoMakerSetup", "Video codec"))
        self.video_codec_dropdown.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>VideoMaker is using OpenCV\'s cv2.VideoWriter class under the hood. This class requires some matching of compatible video codecs, containers, fps, and resolutions. This can be somewhat of a challenge because video codecs are confusing and difficult to install correctly. Basically, it\'s hard to predict which codecs the end user may have installed etc... Therefore, I have made many options available so the end user may experiment and see what works.</p><p>There is a good H264 codec available here: <a href=\"https://github.com/cisco/openh264/releases\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/cisco/openh264/releases</span></a></p><p>Just download the correct one for your OS, extract it and place it in the same directory as your python.exe. Version 1.8.0 was required for Python 3.8.</p><p>Here are some combinations which worked for me:</p><p>Codec | Container</p><p>avc3 | mp4</p><p>avc1 | mov</p><p>x264 | mkv</p></body></html>"))
        self.container_label.setText(_translate("VideoMakerSetup", "Container"))
        self.container_dropdown.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>VideoMaker is using OpenCV\'s cv2.VideoWriter class under the hood. This class requires some matching of compatible video codecs, containers, fps, and resolutions. This can be somewhat of a challenge because video codecs are confusing and difficult to install correctly. Basically, it\'s hard to predict which codecs the end user may have installed etc... Therefore, I have made many options available so the end user may experiment and see what works.</p><p>There is a good H264 codec available here: <a href=\"https://github.com/cisco/openh264/releases\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/cisco/openh264/releases</span></a></p><p>Just download the correct one for your OS, extract it and place it in the same directory as your python.exe. Version 1.8.0 was required for Python 3.8.</p><p>Here are some combinations which worked for me:</p><p>Codec | Container</p><p>avc3 | mp4</p><p>avc1 | mov</p><p>x264 | mkv</p></body></html>"))
        self.resolution_label.setText(_translate("VideoMakerSetup", "Resolution"))
        self.fps_label.setText(_translate("VideoMakerSetup", "Frame rate"))
        self.fps_entry.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>The number of images which will be used to generate a second of video.</p></body></html>"))
        self.fps_entry.setText(_translate("VideoMakerSetup", "60"))
        self.resolution_label_4.setText(_translate("VideoMakerSetup", "Sampling method"))
        self.sampling_method_dropdown.setToolTip(_translate("VideoMakerSetup", "<html><head/><body><p>Perhaps you have a very large set of images and want to use a subset as to reduce computation time and the length of the video. These sampling methods allow you to achieve this. The exponential decay is particuarly useful for conventional ImageEvo outputs as it samples more frequently when there is large changes in fitness but less frequently when there is smaller change in fitness.</p></body></html>"))
        self.label.setText(_translate("VideoMakerSetup", "Start"))
        self.label_2.setText(_translate("VideoMakerSetup", "Step"))
        self.label_4.setText(_translate("VideoMakerSetup", "Stop"))
        self.run_button.setText(_translate("VideoMakerSetup", "Run"))
        self.exit_button.setText(_translate("VideoMakerSetup", "Exit"))
