# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_maker_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoMaker(object):
    def setupUi(self, VideoMaker):
        VideoMaker.setObjectName("VideoMaker")
        VideoMaker.resize(357, 210)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoMaker.sizePolicy().hasHeightForWidth())
        VideoMaker.setSizePolicy(sizePolicy)
        VideoMaker.setMinimumSize(QtCore.QSize(357, 210))
        VideoMaker.setMaximumSize(QtCore.QSize(357, 210))
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoMaker)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_3 = QtWidgets.QFrame(VideoMaker)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_2 = QtWidgets.QFrame(VideoMaker)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.progress_bar_label = QtWidgets.QLabel(VideoMaker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar_label.sizePolicy().hasHeightForWidth())
        self.progress_bar_label.setSizePolicy(sizePolicy)
        self.progress_bar_label.setMinimumSize(QtCore.QSize(300, 0))
        self.progress_bar_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.progress_bar_label.setText("")
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.horizontalLayout_31.addWidget(self.progress_bar_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.progress_bar = QtWidgets.QProgressBar(VideoMaker)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.done_label = QtWidgets.QLabel(VideoMaker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_label.sizePolicy().hasHeightForWidth())
        self.done_label.setSizePolicy(sizePolicy)
        self.done_label.setMinimumSize(QtCore.QSize(45, 0))
        self.done_label.setMaximumSize(QtCore.QSize(45, 16777215))
        self.done_label.setObjectName("done_label")
        self.horizontalLayout_59.addWidget(self.done_label)
        self.done_value = QtWidgets.QLabel(VideoMaker)
        self.done_value.setText("")
        self.done_value.setObjectName("done_value")
        self.horizontalLayout_59.addWidget(self.done_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.total_label = QtWidgets.QLabel(VideoMaker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_label.sizePolicy().hasHeightForWidth())
        self.total_label.setSizePolicy(sizePolicy)
        self.total_label.setMinimumSize(QtCore.QSize(45, 0))
        self.total_label.setMaximumSize(QtCore.QSize(45, 16777215))
        self.total_label.setObjectName("total_label")
        self.horizontalLayout_68.addWidget(self.total_label)
        self.total_value = QtWidgets.QLabel(VideoMaker)
        self.total_value.setText("")
        self.total_value.setObjectName("total_value")
        self.horizontalLayout_68.addWidget(self.total_value)
        self.back_button = QtWidgets.QPushButton(VideoMaker)
        self.back_button.setMinimumSize(QtCore.QSize(80, 27))
        self.back_button.setMaximumSize(QtCore.QSize(80, 27))
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_68.addWidget(self.back_button)
        self.exit_button = QtWidgets.QPushButton(VideoMaker)
        self.exit_button.setMinimumSize(QtCore.QSize(80, 27))
        self.exit_button.setMaximumSize(QtCore.QSize(80, 27))
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_68.addWidget(self.exit_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_68)
        self.line = QtWidgets.QFrame(VideoMaker)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_4 = QtWidgets.QFrame(VideoMaker)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(VideoMaker)
        QtCore.QMetaObject.connectSlotsByName(VideoMaker)

    def retranslateUi(self, VideoMaker):
        _translate = QtCore.QCoreApplication.translate
        VideoMaker.setWindowTitle(_translate("VideoMaker", "𝕀mage𝔼vo"))
        self.progress_bar_label.setToolTip(_translate("VideoMaker", "The input file path (supported types: jpg, jpeg, jpe, jfif, png)"))
        self.done_label.setText(_translate("VideoMaker", "Done:"))
        self.total_label.setText(_translate("VideoMaker", "Total:"))
        self.back_button.setText(_translate("VideoMaker", "Back"))
        self.exit_button.setText(_translate("VideoMaker", "Exit"))

