# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_maker_prompt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoMakerPrompt(object):
    def setupUi(self, VideoMakerPrompt):
        VideoMakerPrompt.setObjectName("VideoMakerPrompt")
        VideoMakerPrompt.resize(357, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoMakerPrompt.sizePolicy().hasHeightForWidth())
        VideoMakerPrompt.setSizePolicy(sizePolicy)
        VideoMakerPrompt.setMinimumSize(QtCore.QSize(357, 150))
        VideoMakerPrompt.setMaximumSize(QtCore.QSize(357, 151))
        VideoMakerPrompt.setSizeIncrement(QtCore.QSize(336, 0))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(VideoMakerPrompt)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_4 = QtWidgets.QFrame(VideoMakerPrompt)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_3 = QtWidgets.QFrame(VideoMakerPrompt)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.label_2 = QtWidgets.QLabel(VideoMakerPrompt)
        self.label_2.setMinimumSize(QtCore.QSize(0, 27))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_75.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_75)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.line_5 = QtWidgets.QFrame(VideoMakerPrompt)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.yes_button = QtWidgets.QPushButton(VideoMakerPrompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yes_button.sizePolicy().hasHeightForWidth())
        self.yes_button.setSizePolicy(sizePolicy)
        self.yes_button.setMinimumSize(QtCore.QSize(80, 27))
        self.yes_button.setMaximumSize(QtCore.QSize(80, 27))
        self.yes_button.setToolTip("")
        self.yes_button.setObjectName("yes_button")
        self.horizontalLayout_76.addWidget(self.yes_button)
        self.no_button = QtWidgets.QPushButton(VideoMakerPrompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.no_button.sizePolicy().hasHeightForWidth())
        self.no_button.setSizePolicy(sizePolicy)
        self.no_button.setMinimumSize(QtCore.QSize(80, 27))
        self.no_button.setMaximumSize(QtCore.QSize(80, 27))
        self.no_button.setToolTip("")
        self.no_button.setObjectName("no_button")
        self.horizontalLayout_76.addWidget(self.no_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_76)
        self.line_2 = QtWidgets.QFrame(VideoMakerPrompt)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(VideoMakerPrompt)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)

        self.retranslateUi(VideoMakerPrompt)
        QtCore.QMetaObject.connectSlotsByName(VideoMakerPrompt)

    def retranslateUi(self, VideoMakerPrompt):
        _translate = QtCore.QCoreApplication.translate
        VideoMakerPrompt.setWindowTitle(_translate("VideoMakerPrompt", "𝕀mage𝔼vo"))
        self.label_2.setText(_translate("VideoMakerPrompt", "Start Video Maker?"))
        self.yes_button.setText(_translate("VideoMakerPrompt", "Yes"))
        self.no_button.setText(_translate("VideoMakerPrompt", "No"))

